name: SimpleSurvivalGame
version: 1.0.0
main: com.myplugin.survival.SimpleSurvivalGame
api-version: 1.20 # 사용하는 마인크래프트 버전에 맞게 수정하세요 (예: 1.16, 1.18 등)
commands:
  startsurvival:
    description: Start the simple survival game.
    usage: /startsurvival
    permission: simplegame.start # 권한 부여